### ISSUE TITLE
Feature request: please add channel name and date to the filename

### ISSUE THREAD

**Issue by TheGhost78** [kannagi0303/yt-dlp-gui#71] opened 2023-03-05 16:12 UTC
Please could you add the option to have the channel name and date in the filename? For example:
Channel Name - YYYY-MM-DD - Video Title.extension

Could you add the option to minimise the program to the tray?

Could you add the option to only download mp4/m4a or webm/OPUS?

**Comment by kannagi0303** [comment] 2023-03-05 21:08
Thank you for using and providing feedback.

You can refer to the following two articles:
- [Use Configuration](https://github.com/kannagi0303/yt-dlp-gui/wiki/Use-Configuration)
- [OUTPUT TEMPLATE](https://github.com/yt-dlp/yt-dlp#output-template)

Then modify the Configuration content to the format you want, for example:
```
-o "%(channel)s - %(upload_date)s - %(title)s.%(ext)s"
```

If you only want to download a specific format, you can choose the format in "Formats" or click the icon on the right side of the drop-down menu to only download the video or audio part.

If you want it to default to mp4/m4a format, you can also change it through Configuration:
```
-f "bv*[ext=mp4]+ba[ext=m4a]/bv*+ba/b"
```
refer to [FORMAT SELECTION](https://github.com/yt-dlp/yt-dlp#format-selection)


I hope this information can help you.

**Comment by TheGhost78** [comment] 2023-03-06 02:11
Thanks! How do I set the location for the temporary files?

**Comment by kannagi0303** [comment] 2023-03-06 03:06
refer to #27 

A simple answer is: Currently, it is not possible to set a custom temporary location.

Currently, the video files are first stored in the folder where yt-dlp-gui.exe is located, and then merged into the destination folder after the download is complete. For live streams, they are directly saved to the destination folder.

I hope this helps!

**Comment by kannagi0303** [comment] 2023-03-08 05:45
Hello, I have released another new version that allows you to customize the location of the temporary folder.
If you are interested, please try the new version. Thank you.

**Closed by kannagi0303** 2023-03-08 05:45 UTC

**Comment by TheGhost78** [comment] 2023-03-08 15:47
Thanks! I’ll try it tonight.

Regards

On 8 Mar 2023, at 05:46, カンナギ ***@***.***> wrote:

﻿

Hello, I have released another new version that allows you to customize the location of the temporary folder.
If you are interested, please try the new version. Thank you.

**Comment by TheGhost78** [comment] 2023-03-08 23:03
Great work so far!

New issue: the cancel button does not work. Try it with a Rumble video link. Same thing occasionally happens with some YouTube video links. The cancel button has a spinner on it but nothing happens when you click it – and all you can do is close the program and open it again.

Enhancement: allow minimise to tray. It would be good to have tray behaviour similar to ClipGrab – when you copy a link, the program activates the window from the tray.

**Comment by kannagi0303** [comment] 2023-03-08 23:25
Hello.

I don't have enough information to detect the issue you mentioned. If you're willing, please provide your operation sequence and URL so that I can reproduce the problem you encountered.

As for the feature of being resident in the tray bar, I can implement it, but I am not inclined to do so mainly because I did not consider resource release or recycling functions from the design stage, and I cannot guarantee that it will not slow down or occupy too many resources on the user's computer. Long-term monitoring of the clipboard may also slow down other applications that use the clipboard function. However, I will still consider this feature depending on the demand.

Also, I would like to request that if possible, please create new Issues on GitHub for different categories or different types of responses. This makes it easier for me to manage and respond to various issues from all users and is less likely to be overlooked. When replying to emails, there may be extra information such as sender and recipient privacy information, which makes reading more difficult.

Sorry, I will edit your message and remove the sender and recipient information first. Please understand.
